### ISSUE TITLE
Lexer is not passing operator test and string test

### ISSUE THREAD

**Issue by kenneth-rosario** [milton-pagan/restest#5]

**Comment by milton-pagan** [comment]
Maybe the word operators and, or, and not should be classified as keywords and not operators. I think that could solve that issue. 

EDIT: I checked python's specification and this is exactly what it does:
[https://docs.python.org/3/reference/lexical_analysis.html#keywords](url)

**Comment by milton-pagan** [comment]
Also, found that changing our String matching regular expression from:
`r'"([^"\n]|[\\"])*"'`
to
`r'"([^"\n]|(\\"))*"'`
fixes the string problems. Not sure of the reason behind this.

**Comment by kenneth-rosario** [comment]
Perfect, lets use the python lexical specifications to guide us. Great find, thank you, I will go ahead and review your code and comment on your pull request when I am done.
