### ISSUE TITLE
Grammar Rules and Parser Development

### ISSUE THREAD

**Issue by kenneth-rosario** [milton-pagan/restest#7]
Start development of grammer rules and developing the parser.

**Comment by kenneth-rosario** [comment]
https://www.youtube.com/watch?v=Zbk0lic04SI . Good you tube tutorial

**Comment by JaviCuebas** [comment]
Gracias Kenny boi

**Comment by kenneth-rosario** [comment]
https://www.youtube.com/channel/UCovR8D97-8qmQ8hWQW0d3ew tiene tres videos de crear un pl
